# **Topic Modelling**

## Dataset

link youtube https://www.youtube.com/watch?v=DgdOQe4aQwU

In [ ]:
import pandas as pd
from googleapiclient.discovery import build

In [ ]:
def video_comments(video_id):
	# empty list for storing reply
	replies = []

	# creating youtube resource object
	youtube = build('youtube', 'v3', developerKey=api_key)

	# retrieve youtube video results
	video_response = youtube.commentThreads().list(part='snippet,replies', videoId=video_id).execute()

	# iterate video response
	while video_response:
		
		# extracting required info
		# from each result object
		for item in video_response['items']:
			
			# Extracting comments ()
			published = item['snippet']['topLevelComment']['snippet']['publishedAt']
			user = item['snippet']['topLevelComment']['snippet']['authorDisplayName']

			# Extracting comments
			comment = item['snippet']['topLevelComment']['snippet']['textDisplay']
			likeCount = item['snippet']['topLevelComment']['snippet']['likeCount']

			replies.append([published, user, comment, likeCount])
			
			# counting number of reply of comment
			replycount = item['snippet']['totalReplyCount']

			# if reply is there
			if replycount>0:
				# iterate through all reply
				for reply in item['replies']['comments']:
					
					# Extract reply
					published = reply['snippet']['publishedAt']
					user = reply['snippet']['authorDisplayName']
					repl = reply['snippet']['textDisplay']
					likeCount = reply['snippet']['likeCount']
					
					# Store reply is list
					#replies.append(reply)
					replies.append([published, user, repl, likeCount])

			# print comment with list of reply
			#print(comment, replies, end = '\n\n')

			# empty reply list
			#replies = []

		# Again repeat
		if 'nextPageToken' in video_response:
			video_response = youtube.commentThreads().list(
					part = 'snippet,replies',
					pageToken = video_response['nextPageToken'], 
					videoId = video_id
				).execute()
		else:
			break
	#endwhile
	return replies

In [ ]:
api_key = 'AIzaSyD6Lb7fJBcMcxcvKsIRctUXv_bwTyxc56w' 
# url = https://www.youtube.com/watch?v=DgdOQe4aQwU
video_id = "DgdOQe4aQwU" #id video
# Call function
comments = video_comments(video_id)
comments

[['2023-05-05T07:47:21Z',
  'Nurul Izza',
  'Yg lebih yakin menangx,,, seandainya pak Prabowo berpasangan dgn Pak Anis. Tp masalahnya siapa yg mau ngalah jd cawapres, krn dua2x bisa capres. Itu peluangx menurut aku, 99%.',
  0],
 ['2023-05-05T07:43:42Z',
  'Nurul Izza',
  'Ya,,, pasti diusahakan lebih dari 2 pasang capres untuk memenangkan pak Ganjar, kalau cuma 2 pasang, pak Anis dan pak Ganjar aja, kemenangan pak Anis 80% jadi kalau bisa calon2 yg peluangnya tipis, beri laluan ke pak Anis aja, gak usah maju, karena itu akan memecah suara aja.',
  0],
 ['2023-05-05T04:08:34Z', 'izmail exact', 'Mahfud MD', 0],
 ['2023-05-04T18:31:41Z', 'Qolis Fuadi', 'ANIES &amp; ERICK = SEMPURNA', 0],
 ['2023-05-02T16:30:21Z',
  'Warta Dunia Official',
  'Media dan pengamat di bodohi dan di bohongi oleh dagelan politik penguasa dan kroni - kroni nya...Hancur sudah sistim demokrasi Indonesia saat ini akibat ambisi dan keserakahan...<br><br>Rakyat Indonesia tidak bisa di bodohi dan di bohongi lagi...',


In [ ]:
df = pd.DataFrame(comments, columns=['publishedAt', 'authorDisplayName', 'textDisplay', 'likeCount'])
df

publishedAt              authorDisplayName  \
0   2023-05-05T07:47:21Z                     Nurul Izza   
1   2023-05-05T07:43:42Z                     Nurul Izza   
2   2023-05-05T04:08:34Z                   izmail exact   
3   2023-05-04T18:31:41Z                    Qolis Fuadi   
4   2023-05-02T16:30:21Z           Warta Dunia Official   
5   2023-05-02T09:28:42Z                  Pekak Ajusszz   
6   2023-04-30T23:35:35Z                    WAN RAHMADI   
7   2023-04-30T15:17:37Z               APTA  HOBI JOGET   
8   2023-04-30T14:45:52Z                      Den Dayen   
9   2023-04-29T08:56:57Z                  Riana Cecilia   
10  2023-04-29T08:33:15Z                  Ahmad Baidawi   
11  2023-04-29T07:02:21Z                     Ahmad Dewi   
12  2023-05-08T14:06:25Z                    Dana Kusuma   
13  2023-04-29T04:38:46Z       Helmi pindra Helm pindra   
14  2023-04-29T03:39:58Z                           E_NS   
15  2023-04-28T12:48:29Z                  Wibowo Wibowo   
16  2023-04-28T08:40:44Z                    Garam dapur   
17  2023-05-03T11:59:02Z                 Wandi.setiawan   
18  2023-04-29T03:31:50Z                     James Bond   
19  2023-04-28T08:36:23Z              romansa kehidupan   
20  2023-04-28T08:35:03Z              romansa kehidupan   
21  2023-05-02T19:55:27Z             Andrea Jussienando   
22  2023-04-28T08:24:34Z                        Ph Oppo   
23  2023-04-28T07:53:35Z          MD SUARA RAKYAT TOLIS   
24  2023-05-08T14:07:33Z                    Dana Kusuma   
25  2023-04-28T13:27:56Z          MD SUARA RAKYAT TOLIS   
26  2023-04-28T08:35:02Z                       cukufalu   
27  2023-04-28T07:48:18Z                  lambe turahan   
28  2023-04-30T13:54:24Z                  lambe turahan   
29  2023-04-30T13:50:02Z                  lambe turahan   
30  2023-04-30T13:40:12Z                    Hanrecovery   
31  2023-04-30T09:00:22Z                  lambe turahan   
32  2023-04-30T07:33:58Z                    Hanrecovery   
33  2023-04-28T07:46:35Z                     husnedi 01   
34  2023-04-28T07:44:31Z              Dara sabila Putri   
35  2023-04-28T07:41:10Z                     Mhd Syukur   
36  2023-04-28T07:20:22Z                  Adiyanto Amri   
37  2023-04-28T07:14:07Z                 young socrates   
38  2023-04-28T07:10:08Z                      Ali Utomo   
39  2023-04-28T07:09:00Z         Chusu inspirator negri   
40  2023-05-09T09:18:10Z  Juanda Ottodinata Linggabuana   
41  2023-04-29T03:51:36Z         Chusu inspirator negri   
42  2023-04-29T03:37:56Z                     James Bond   
43  2023-04-28T10:39:55Z                       Alamsyah   
44  2023-04-28T10:36:07Z         Chusu inspirator negri   
45  2023-04-28T07:06:36Z            Fahluzy76 Fahluzy76   
46  2023-04-28T07:04:35Z                Subagio Subagio   
47  2023-05-03T15:32:32Z                  lambe turahan   
48  2023-05-03T03:09:02Z                   Pangat Bador   
49  2023-04-30T13:56:25Z                  lambe turahan   
50  2023-04-28T06:51:38Z                   Vicky Andrea   
51  2023-04-28T07:20:38Z            Sohibandi Sohibandi   
52  2023-04-28T07:15:27Z                 young socrates   
53  2023-04-28T07:08:12Z                      Duni Duni   

                                          textDisplay  likeCount  
0   Yg lebih yakin menangx,,, seandainya pak Prabo...          0  
1   Ya,,, pasti diusahakan lebih dari 2 pasang cap...          0  
2                                           Mahfud MD          0  
3                        ANIES &amp; ERICK = SEMPURNA          0  
4   Media dan pengamat di bodohi dan di bohongi ol...          0  
5   Masukan aja...ini NKRI dari sabang sampai Mera...          0  
6   Semoga presiden berikutnya mau menyedekahkan h...          0  
7                               Mahfud ahok indpenden          0  
8   kalau TGB di surve baru kita percaya,,,memg ke...          1  
9   Sy sangat setuju lebih banyak capres cawapres ...          0  
10  Yaa mau poros apapun pak p

In [ ]:
# df.to_csv("capres2024.csv",index=False)

## Preprocessing

In [ ]:
!pip install Sastrawi

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import pandas as pd
import numpy as np
from nltk.corpus import stopwords
import re
import nltk
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from nltk.tokenize import sent_tokenize, word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
dt = pd.read_csv("/content/drive/MyDrive/prosain/tugas/capres2024.csv")
dt

publishedAt              authorDisplayName  \
0   2023-05-05T07:47:21Z                     Nurul Izza   
1   2023-05-05T07:43:42Z                     Nurul Izza   
2   2023-05-05T04:08:34Z                   izmail exact   
3   2023-05-04T18:31:41Z                    Qolis Fuadi   
4   2023-05-02T16:30:21Z           Warta Dunia Official   
5   2023-05-02T09:28:42Z                  Pekak Ajusszz   
6   2023-04-30T23:35:35Z                    WAN RAHMADI   
7   2023-04-30T15:17:37Z               APTA  HOBI JOGET   
8   2023-04-30T14:45:52Z                      Den Dayen   
9   2023-04-29T08:56:57Z                  Riana Cecilia   
10  2023-04-29T08:33:15Z                  Ahmad Baidawi   
11  2023-04-29T07:02:21Z                     Ahmad Dewi   
12  2023-05-08T14:06:25Z                    Dana Kusuma   
13  2023-04-29T04:38:46Z       Helmi pindra Helm pindra   
14  2023-04-29T03:39:58Z                           E_NS   
15  2023-04-28T12:48:29Z                  Wibowo Wibowo   
16  2023-04-28T08:40:44Z                    Garam dapur   
17  2023-05-03T11:59:02Z                 Wandi.setiawan   
18  2023-04-29T03:31:50Z                     James Bond   
19  2023-04-28T08:36:23Z              romansa kehidupan   
20  2023-04-28T08:35:03Z              romansa kehidupan   
21  2023-05-02T19:55:27Z             Andrea Jussienando   
22  2023-04-28T08:24:34Z                        Ph Oppo   
23  2023-04-28T07:53:35Z          MD SUARA RAKYAT TOLIS   
24  2023-05-08T14:07:33Z                    Dana Kusuma   
25  2023-04-28T13:27:56Z          MD SUARA RAKYAT TOLIS   
26  2023-04-28T08:35:02Z                       cukufalu   
27  2023-04-28T07:48:18Z                  lambe turahan   
28  2023-04-30T13:54:24Z                  lambe turahan   
29  2023-04-30T13:50:02Z                  lambe turahan   
30  2023-04-30T13:40:12Z                    Hanrecovery   
31  2023-04-30T09:00:22Z                  lambe turahan   
32  2023-04-30T07:33:58Z                    Hanrecovery   
33  2023-04-28T07:46:35Z                     husnedi 01   
34  2023-04-28T07:44:31Z              Dara sabila Putri   
35  2023-04-28T07:41:10Z                     Mhd Syukur   
36  2023-04-28T07:20:22Z                  Adiyanto Amri   
37  2023-04-28T07:14:07Z                 young socrates   
38  2023-04-28T07:10:08Z                      Ali Utomo   
39  2023-04-28T07:09:00Z         Chusu inspirator negri   
40  2023-05-09T09:18:10Z  Juanda Ottodinata Linggabuana   
41  2023-04-29T03:51:36Z         Chusu inspirator negri   
42  2023-04-29T03:37:56Z                     James Bond   
43  2023-04-28T10:39:55Z                       Alamsyah   
44  2023-04-28T10:36:07Z         Chusu inspirator negri   
45  2023-04-28T07:06:36Z            Fahluzy76 Fahluzy76   
46  2023-04-28T07:04:35Z                Subagio Subagio   
47  2023-05-03T15:32:32Z                  lambe turahan   
48  2023-05-03T03:09:02Z                   Pangat Bador   
49  2023-04-30T13:56:25Z                  lambe turahan   
50  2023-04-28T06:51:38Z                   Vicky Andrea   
51  2023-04-28T07:20:38Z            Sohibandi Sohibandi   
52  2023-04-28T07:15:27Z                 young socrates   
53  2023-04-28T07:08:12Z                      Duni Duni   

                                          textDisplay  likeCount  
0   Yg lebih yakin menangx,,, seandainya pak Prabo...          0  
1   Ya,,, pasti diusahakan lebih dari 2 pasang cap...          0  
2                                           Mahfud MD          0  
3                              ANIES ERICK = SEMPURNA          0  
4   Media dan pengamat di bodohi dan di bohongi ol...          0  
5   Masukan aja...ini NKRI dari sabang sampai Mera...          0  
6   Semoga presiden berikutnya mau menyedekahkan h...          0  
7                               Mahfud ahok indpenden          0  
8   kalau TGB di surve baru kita percaya,,,memg ke...          1  
9   Sy sangat setuju lebih banyak capres cawapres ...          0  
10  Yaa mau poros apapun pak p

In [ ]:
#cleaningtext
clean_tag = re.compile('@\S+')
clean_url = re.compile('https?:\/\/.*[\r\n]*')
clean_hastag = re.compile('#\S+')
clean_symbol = re.compile('[^a-zA-Z]')
def clean_punct(text):
    text = clean_tag.sub('', text)
    text = clean_url.sub('', text)
    text = clean_hastag.sub(' ', text)
    text = clean_symbol.sub(' ', text)
    return text
# Buat kolom tambahan untuk data description setelah dilakukan clean 
preproces= dt['textDisplay'].apply(clean_punct)
dt_clean=pd.DataFrame(preproces)
dt_clean

textDisplay
0   Yg lebih yakin menangx    seandainya pak Prabo...
1   Ya    pasti diusahakan lebih dari   pasang cap...
2                                           Mahfud MD
3                              ANIES ERICK   SEMPURNA
4   Media dan pengamat di bodohi dan di bohongi ol...
5   Masukan aja   ini NKRI dari sabang sampai Mera...
6   Semoga presiden berikutnya mau menyedekahkan h...
7                               Mahfud ahok indpenden
8   kalau TGB di surve baru kita percaya   memg ke...
9   Sy sangat setuju lebih banyak capres cawapres ...
10  Yaa mau poros apapun pak prabowo tetap setia p...
11         Ujung ujung cuma ada   poross   Maksimal  
12  Msh yakin yg maju pilpres hanya   poros     lo...
13                        Anis rk nasdem pks demokrat
14  Pak Anies Rasyid Baswedan Dan Pak Agus Harimur...
15  SAYA AKAN SANGAT SENANG JIKA YOHANES GAGAL NYA...
16  Golkar harus berani mandiri jangan jadi pengek...
17                                               GPRK
18  Aerlangga cak imin vs prabowo erik vs ganjar s...
19  Jangan biarkan pelangar Ham berat memimpin neg...
20  Cuma aniss sang satrioo paningit yg akan memba...
21  Tidak ada satrio piningit dari Yaman dulu        
22                                            Bos men
23          Intinya Rakyat hanya butuh Annis baswedan
24                                                   
25   Rakyat yang mau keadilan bagi semua golongan ...
26                        Rakyat yang mana Bro       
27  poros tengah  poros terakhir biasanya pemenang...
28   Prasetyo Insani agama di gunakan untuk kepent...
29                                  ahoknya juga ogah
30    turahan dibayar pun  lembaga survey nya ogah   
31   sebab ahok gak mau membayar lembaga survey ka...
32   turahan lembaga survey pun gk bakal kepikiran...
33  Pusing amat Calonkan saja    Anies baswedan  G...
34                       Ujungnya  ujungnya dua poros
35  Apapun yg ada  yg pasti partai Nasdem akhirnya...
36  Poros baru koalisi perubahan bubar dan koalisi...
37  PAN sebelumnya sudah mengusulkan  quot Ganjar ...
38                                         poros     
39  Golkar  jadikan   poros sama pan  masih ada Ri...
40  Setuju ayo bikin   poros Ridwan Kamil   Eric T...
41                   Bond biar lebih seru klo   poros
42  Pan mengusung Erik berpasangan dg prabowo    K...
43   inspirator negri yakin pilpres aman dan menye...
44   iya hehe Ayo bikin poros ke   C  Saya menduku...
45  PPP akan menyusul Hanura yg suaranya hilang di...
46  saya kira tdk ada lagi poros baru  Karena pelu...
47                                  Bador lebih parah
48                     turahan dari pada budak partai
49  jangan biarkan presiden republik indonesa jadi...
50  Siapapun capres cawapres dari lingkaran JKW  G...
51  GK NGARUH   OPI UNTUNGE TAMBAH  AWAKMU   NTAR ...
52  Lu mau mati juga nggak ngaruh  lu itu siapa   ...
53                        Iya lah org buzzer anis

In [ ]:
#lowercase
def clean_lower(lwr):
    lwr = lwr.lower() # lowercase text
    return lwr
# Buat kolom tambahan untuk data description yang telah dicasefolding  
dt_clean = dt_clean['textDisplay'].apply(clean_lower)
dt_lowecase=pd.DataFrame(dt_clean)
dt_lowecase

textDisplay
0   yg lebih yakin menangx    seandainya pak prabo...
1   ya    pasti diusahakan lebih dari   pasang cap...
2                                           mahfud md
3                              anies erick   sempurna
4   media dan pengamat di bodohi dan di bohongi ol...
5   masukan aja   ini nkri dari sabang sampai mera...
6   semoga presiden berikutnya mau menyedekahkan h...
7                               mahfud ahok indpenden
8   kalau tgb di surve baru kita percaya   memg ke...
9   sy sangat setuju lebih banyak capres cawapres ...
10  yaa mau poros apapun pak prabowo tetap setia p...
11         ujung ujung cuma ada   poross   maksimal  
12  msh yakin yg maju pilpres hanya   poros     lo...
13                        anis rk nasdem pks demokrat
14  pak anies rasyid baswedan dan pak agus harimur...
15  saya akan sangat senang jika yohanes gagal nya...
16  golkar harus berani mandiri jangan jadi pengek...
17                                               gprk
18  aerlangga cak imin vs prabowo erik vs ganjar s...
19  jangan biarkan pelangar ham berat memimpin neg...
20  cuma aniss sang satrioo paningit yg akan memba...
21  tidak ada satrio piningit dari yaman dulu        
22                                            bos men
23          intinya rakyat hanya butuh annis baswedan
24                                                   
25   rakyat yang mau keadilan bagi semua golongan ...
26                        rakyat yang mana bro       
27  poros tengah  poros terakhir biasanya pemenang...
28   prasetyo insani agama di gunakan untuk kepent...
29                                  ahoknya juga ogah
30    turahan dibayar pun  lembaga survey nya ogah   
31   sebab ahok gak mau membayar lembaga survey ka...
32   turahan lembaga survey pun gk bakal kepikiran...
33  pusing amat calonkan saja    anies baswedan  g...
34                       ujungnya  ujungnya dua poros
35  apapun yg ada  yg pasti partai nasdem akhirnya...
36  poros baru koalisi perubahan bubar dan koalisi...
37  pan sebelumnya sudah mengusulkan  quot ganjar ...
38                                         poros     
39  golkar  jadikan   poros sama pan  masih ada ri...
40  setuju ayo bikin   poros ridwan kamil   eric t...
41                   bond biar lebih seru klo   poros
42  pan mengusung erik berpasangan dg prabowo    k...
43   inspirator negri yakin pilpres aman dan menye...
44   iya hehe ayo bikin poros ke   c  saya menduku...
45  ppp akan menyusul hanura yg suaranya hilang di...
46  saya kira tdk ada lagi poros baru  karena pelu...
47                                  bador lebih parah
48                     turahan dari pada budak partai
49  jangan biarkan presiden republik indonesa jadi...
50  siapapun capres cawapres dari lingkaran jkw  g...
51  gk ngaruh   opi untunge tambah  awakmu   ntar ...
52  lu mau mati juga nggak ngaruh  lu itu siapa   ...
53                        iya lah org buzzer anis

In [ ]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
!pip install indoNLP

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
slang_dict = pd.read_csv("https://raw.githubusercontent.com/DwiAsfi/prosaindata/main/slank.txt", sep=" ", header=None)
from indoNLP.preprocessing import replace_slang
from indoNLP.preprocessing import replace_word_elongation
replace_slang
def replace_slang_words(text):
    words = nltk.word_tokenize(text.lower())
    words_filtered = [word for word in words if word not in stopwords.words('indonesian')]
    for i in range(len(words_filtered)):
        if words_filtered[i] in slang_dict:
            words_filtered[i] = slang_dict[words_filtered[i]]
    return ' '.join(words_filtered)

# penggunaan
dt_lowecase=[]
for i in range(len(dt_clean)):
  dt_lowecase.append(dt_clean[i])

slang_words=[]
for i in range(len(dt_lowecase)):
  slang = replace_slang_words(dt_lowecase[i])
  y=replace_slang(slang)
  slang_words.append(y)

slang = pd.DataFrame(slang_words, columns=["Slank"])
slang

Slank
0   yang menangx seandainya prabowo berpasangan de...
1   ya diusahakan pasang capres memenangkan ganjar...
2                                           mahfud md
3                                anies erick sempurna
4   media pengamat bodohi bohongi dagelan politik ...
5   masukan saja nkri sabang meraoke cawapres indo...
6   semoga presiden menyedekahkan hartanya masyara...
7                               mahfud ahok indpenden
8   tgb surve percaya memg kenyataan safari pengaj...
9   saya setuju capres cawapres pilihan rakyat bia...
10  ya poros apapun prabowo setia bendera merah putih
11                        ujung ujung poross maksimal
12  masih yang maju pilpres poros logistik pilpres...
13                        anis rk nasdem pks demokrat
14  anies rasyid baswedan agus harimurti yudhoyono...
15  senang yohanes gagal nyapres pilpres aman dama...
16                     golkar berani mandiri pengekor
17                                               gprk
18  aerlangga cak imin vs prabowo erik vs ganjar s...
19  biarkan pelangar ham berat memimpin negriii ko...
20  aniss sang satrioo paningit yang membawa kemak...
21                              satrio piningit yaman
22                                            bos men
23                intinya rakyat butuh annis baswedan
24                                                   
25  rakyat keadilan golongan rakyat perubahan hany...
26                                         rakyat bro
27  poros poros pemenangnya seandainya saya jadi k...
28  prasetyo insani agama kepentingan politik agam...
29                                       ahoknya ogah
30            turahan dibayar lembaga survey nya ogah
31  ahok enggak membayar lembaga survey kali yang ...
32  turahan lembaga survey enggak kepikiran nama a...
33  pusing calonkan anies baswedan ganjar pranowo ...
34                            ujungnya ujungnya poros
35  apapun yang yang partai nasdem pemerintahan pa...
36  poros koalisi perubahan bubar koalisi prabowo ...
37  kapan mengusulkan quot ganjar erick quot poros...
38                                              poros
39  golkar jadikan poros kapan ridwan kamil erick ...
40  setuju ayo bikin poros ridwan kamil eric thohi...
41                          bond biar seru kalo poros
42  kapan mengusung erik berpasangan dengan prabow...
43          inspirator negeri pilpres aman menyejukan
44  iya hehe ayo bikin poros sih mendukung ridwan ...
45  ppp menyusul hanura yang suaranya hilang parle...
46  tidak poros peluang koalisi sudah habis koalis...
47                                        bador parah
48                               turahan budak partai
49  biarkan presiden republik indonesa petugas partai
50  capres cawapres lingkaran jkw gub palestina wo...
51  enggak ngaruh opi untunge awakmu entar tukang ...
52  lu mati enggak ngaruh lu mengaca lu ya muka jelek
53                              iya orang buzzer anis

In [ ]:
tokenize=[]
for i in range(len(slang_words)):
  token=word_tokenize(slang_words[i])
  tokendata = []
  for x in token :
    tokendata.append(x)
  tokenize.append(tokendata)
  print(tokendata)

['yang', 'menangx', 'seandainya', 'prabowo', 'berpasangan', 'dengan', 'anis', 'tapi', 'yang', 'mengalah', 'jadi', 'cawapres', 'karena', 'kali', 'capres', 'peluangx']
['ya', 'diusahakan', 'pasang', 'capres', 'memenangkan', 'ganjar', 'pasang', 'anis', 'ganjar', 'saja', 'kemenangan', 'anis', 'calon', 'yang', 'peluangnya', 'tipis', 'laluan', 'anis', 'saja', 'enggak', 'maju', 'memecah', 'suara', 'saja']
['mahfud', 'md']
['anies', 'erick', 'sempurna']
['media', 'pengamat', 'bodohi', 'bohongi', 'dagelan', 'politik', 'penguasa', 'kroni', 'kroni', 'nya', 'hancur', 'sistim', 'demokrasi', 'indonesia', 'akibat', 'ambisi', 'keserakahan', 'rakyat', 'indonesia', 'bodohi', 'bohongi']
['masukan', 'saja', 'nkri', 'sabang', 'meraoke', 'cawapres', 'indonesia', 'timur', 'untuk', 'keseimbangan', 'fikir', 'dampak', 'kedepannya', 'nkri', 'yang', 'cintai']
['semoga', 'presiden', 'menyedekahkan', 'hartanya', 'masyarakat', 'yang', 'membutuhkan', 'umar', 'bin', 'khatab', 'yang', 'bergelimang', 'harta', 'rakyatnya

In [ ]:
stopword=[]
for i in range(len(tokenize)):
  listStopword =  set(stopwords.words('indonesian'))
  removed=[]
  for x in (tokenize[i]):
    if x not in listStopword:
       removed.append(x)
  stopword.append(removed)
  print(removed)

['menangx', 'seandainya', 'prabowo', 'berpasangan', 'anis', 'mengalah', 'cawapres', 'kali', 'capres', 'peluangx']
['ya', 'diusahakan', 'pasang', 'capres', 'memenangkan', 'ganjar', 'pasang', 'anis', 'ganjar', 'kemenangan', 'anis', 'calon', 'peluangnya', 'tipis', 'laluan', 'anis', 'maju', 'memecah', 'suara']
['mahfud', 'md']
['anies', 'erick', 'sempurna']
['media', 'pengamat', 'bodohi', 'bohongi', 'dagelan', 'politik', 'penguasa', 'kroni', 'kroni', 'nya', 'hancur', 'sistim', 'demokrasi', 'indonesia', 'akibat', 'ambisi', 'keserakahan', 'rakyat', 'indonesia', 'bodohi', 'bohongi']
['masukan', 'nkri', 'sabang', 'meraoke', 'cawapres', 'indonesia', 'timur', 'keseimbangan', 'fikir', 'dampak', 'kedepannya', 'nkri', 'cintai']
['semoga', 'presiden', 'menyedekahkan', 'hartanya', 'masyarakat', 'membutuhkan', 'umar', 'bin', 'khatab', 'bergelimang', 'harta', 'rakyatnya']
['mahfud', 'ahok', 'indpenden']
['tgb', 'surve', 'percaya', 'memg', 'kenyataan', 'safari', 'pengajian', 'kmna', 'rekam', 'jejak', 'p

In [ ]:
stemming=[]
for i in range(len(stopword)):
  factory = StemmerFactory()
  stemmer = factory.create_stemmer()
  katastem=[]
  for x in (stopword[i]):
    katastem.append(stemmer.stem(x))
  stemming.append(katastem)
  print(katastem)

['menangx', 'anda', 'prabowo', 'pasang', 'anis', 'kalah', 'cawapres', 'kali', 'capres', 'peluangx']
['ya', 'usaha', 'pasang', 'capres', 'menang', 'ganjar', 'pasang', 'anis', 'ganjar', 'menang', 'anis', 'calon', 'peluang', 'tipis', 'lalu', 'anis', 'maju', 'pecah', 'suara']
['mahfud', 'md']
['anies', 'erick', 'sempurna']
['media', 'amat', 'bodoh', 'bohong', 'dagel', 'politik', 'kuasa', 'kroni', 'kroni', 'nya', 'hancur', 'sistim', 'demokrasi', 'indonesia', 'akibat', 'ambisi', 'serakah', 'rakyat', 'indonesia', 'bodoh', 'bohong']
['masuk', 'nkri', 'sabang', 'meraoke', 'cawapres', 'indonesia', 'timur', 'imbang', 'fikir', 'dampak', 'depan', 'nkri', 'cinta']
['moga', 'presiden', 'sedekah', 'harta', 'masyarakat', 'butuh', 'umar', 'bin', 'khatab', 'gelimang', 'harta', 'rakyat']
['mahfud', 'ahok', 'indpenden']
['tgb', 'surve', 'percaya', 'memg', 'nyata', 'safari', 'aji', 'kmna', 'rekam', 'jejak', 'prestasi', 'back', 'round', 'tokoh', 'agama', 'dunia', 'damai', 'agama', 'dunia', 'anggota', 'majlis

In [ ]:
join=[]
for i in range(len(stemming)):
  joinkata = ' '.join(stemming[i])
  join.append(joinkata)

hasilpreproses = pd.DataFrame(join, columns=['Preprocessing'])
hasilpreproses

Preprocessing
0   menangx anda prabowo pasang anis kalah cawapre...
1   ya usaha pasang capres menang ganjar pasang an...
2                                           mahfud md
3                                anies erick sempurna
4   media amat bodoh bohong dagel politik kuasa kr...
5   masuk nkri sabang meraoke cawapres indonesia t...
6   moga presiden sedekah harta masyarakat butuh u...
7                               mahfud ahok indpenden
8   tgb surve percaya memg nyata safari aji kmna r...
9   tuju capres cawapres pilih rakyat biar berjln ...
10     ya poros apa prabowo setia bendera merah putih
11                        ujung ujung poross maksimal
12            maju pilpres poros logistik pilpres bro
13                        anis rk nasdem pks demokrat
14     anies rasyid baswedan agus harimurti yudhoyono
15  senang yohanes gagal nyapres pilpres aman dama...
16                         golkar berani mandiri ekor
17                                               gprk
18  aerlangga cak imin vs prabowo erik vs ganjar s...
19  biar pelangar ham berat pimpin negriii korupto...
20  aniss sang satrioo paningit bawa kemakmutan ja...
21                                satrio pingit yaman
22                                            bos men
23                   inti rakyat butuh annis baswedan
24                                                   
25        rakyat adil golong rakyat ubah cebong takut
26                                         rakyat bro
27  poros poros menang anda tum partai calon ahok ...
28  prasetyo insani agama penting politik agama ku...
29                                       ahoknya ogah
30              turahan bayar lembaga survey nya ogah
31          ahok bayar lembaga survey kali bayar tuju
32        turahan lembaga survey pikir nama ahok list
33  pusing calon anies baswedan ganjar pranowo pra...
34                                  ujung ujung poros
35            apa partai nasdem perintah partai gurem
36  poros koalisi ubah bubar koalisi prabowo bentu...
37                  usul quot ganjar erick quot poros
38                                              poros
39  golkar jadi poros ridwan kamil erick thohir bi...
40  tuju ayo bikin poros ridwan kamil eric thohir ...
41                          bond biar seru kalo poros
42  usung erik pasang prabowo golkar koalisi pkb u...
43               inspirator negeri pilpres aman sejuk
44  iya hehe ayo bikin poros sih dukung ridwan kam...
45       ppp susul hanura suara hilang parlemen usung
46  poros peluang koalisi habis koalisi bubar opos...
47                                        bador parah
48                               turahan budak partai
49       biar presiden republik indonesa tugas partai
50  capres cawapres lingkar jkw gub palestina wowo...
51  ngaruh opi untunge awak entar tukang ngathong ...
52            lu mati ngaruh lu kaca lu ya muka jelek
53                              iya orang buzzer anis

## TF-IDF

In [ ]:
tr_model  = TfidfVectorizer()
tf_vector = tr_model.fit_transform(hasilpreproses['Preprocessing'])

In [ ]:
tf_array = tf_vector.toarray()
print(tf_array)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
words_set = tr_model.get_feature_names_out()
print(words_set)

['adil' 'aerlangga' 'agama' 'agus' 'ahok' 'ahoknya' 'ahy' 'airlangga'
 'aji' 'akal' 'akbar' 'akibat' 'alumni' 'aman' 'amat' 'ambisi' 'anda'
 'anggota' 'anies' 'anis' 'aniss' 'annis' 'apa' 'awak' 'ayo' 'back'
 'bador' 'bangsa' 'barat' 'baswedan' 'bawa' 'bayar' 'beda' 'belaka'
 'beliau' 'bendera' 'bentuk' 'ber' 'berani' 'berat' 'berjln' 'besar'
 'biar' 'bikin' 'bin' 'biyar' 'black' 'bodoh' 'bohong' 'bola' 'bond' 'bos'
 'bro' 'buang' 'bubar' 'budak' 'buru' 'butuh' 'buzzer' 'cak' 'calon'
 'capres' 'cawapres' 'cebong' 'ceramah' 'cinta' 'coba' 'cocok' 'copet'
 'dagel' 'dalil' 'damai' 'dampak' 'daulat' 'demo' 'demokrasi' 'demokrat'
 'dengar' 'depan' 'dgan' 'dicapreskan' 'dinamika' 'dki' 'dlakukan'
 'dukung' 'dunia' 'dur' 'efek' 'ekor' 'elektabilitas' 'entar' 'eric'
 'erick' 'erik' 'faizal' 'fakta' 'fikir' 'gagal' 'ganjar' 'geger'
 'gelandang' 'gelimang' 'gerindra' 'golkar' 'golong' 'goncang' 'gprk'
 'gub' 'gue' 'gurem' 'gus' 'habis' 'hak' 'ham' 'hancur' 'hanura' 'hari'
 'harimurti' 'harta' 'h

In [ ]:
df = pd.DataFrame(tf_array, columns = words_set)
df

adil  aerlangga     agama     agus      ahok   ahoknya       ahy  \
0   0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
1   0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
2   0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
3   0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
4   0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
5   0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
6   0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
7   0.000000   0.000000  0.000000  0.00000  0.516556  0.000000  0.000000   
8   0.000000   0.000000  0.148125  0.00000  0.000000  0.000000  0.000000   
9   0.202926   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
10  0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
11  0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
12  0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
13  0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
14  0.000000   0.000000  0.000000  0.43819  0.000000  0.000000  0.000000   
15  0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
16  0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
17  0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
18  0.000000   0.246918  0.000000  0.00000  0.000000  0.000000  0.228745   
19  0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
20  0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
21  0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
22  0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
23  0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
24  0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
25  0.363456   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
26  0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
27  0.000000   0.000000  0.000000  0.00000  0.379255  0.000000  0.067360   
28  0.000000   0.000000  0.565394  0.00000  0.000000  0.000000  0.000000   
29  0.000000   0.000000  0.000000  0.00000  0.000000  0.741073  0.000000   
30  0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
31  0.000000   0.000000  0.000000  0.00000  0.312000  0.000000  0.000000   
32  0.000000   0.000000  0.000000  0.00000  0.334182  0.000000  0.000000   
33  0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
34  0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
35  0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
36  0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.263658   
37  0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
38  0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
39  0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
40  0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
41  0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
42  0.000000   0.165820  0.000000  0.00000  0.000000  0.000000  0.000000   
43  0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
44  0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
45  0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
46  0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
47  0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
48  0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
49  0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
50  0.000000   0.000000  0.000000  0.00000  0.000000  0.000000  0.000000   
51  0.000000   0.000000  0.000000  0.00000  0.000000  0.

## Singular Value Decomposition

Teknik untuk mendekomposisi matriks berukuran apa saja (biasanya diaplikasikan untuk matriks dengan ukuran sangat besar), untuk mempermudah pengolahan data.

In [ ]:
from sklearn.decomposition import TruncatedSVD
lsa_model = TruncatedSVD(n_components=3, algorithm='randomized', n_iter=10, random_state=42)
lsa_top=lsa_model.fit_transform(df)

In [ ]:
print(lsa_top)
print(lsa_top.shape)  # (no_of_doc*no_of_topics)

[[ 1.78934205e-01  1.01777504e-01 -9.28682317e-02]
 [ 2.33282125e-01  3.38295468e-02 -1.26673995e-01]
 [ 4.04745194e-02  9.43512682e-02  4.48366584e-02]
 [ 1.63383562e-01 -2.93171633e-02 -8.79611481e-02]
 [ 1.07254002e-01  9.81988302e-02 -7.01486706e-02]
 [ 7.08578045e-02  4.89050902e-02 -5.39504470e-02]
 [ 1.55256682e-01  1.23256602e-01 -2.54733187e-01]
 [ 1.18490960e-01  2.55589540e-01  1.38909361e-01]
 [ 7.33885063e-02  1.25618190e-01  4.31228851e-03]
 [ 2.98672619e-01  1.60075950e-01 -2.82566409e-01]
 [ 2.49075722e-01 -9.66572748e-02  1.77555518e-02]
 [ 2.43139170e-01 -3.71253874e-01  3.72529596e-01]
 [ 3.04213457e-01 -1.11676425e-01 -7.49902948e-02]
 [ 8.47321241e-02  4.84865921e-02 -5.67033102e-02]
 [ 9.66313813e-02  3.47981758e-02 -1.50896189e-01]
 [ 9.37329180e-02 -1.26375443e-02 -6.37144158e-02]
 [ 7.57608668e-02  6.17383972e-03 -3.28930754e-02]
 [ 4.29052932e-06 -1.95397218e-04 -1.08392235e-03]
 [ 2.32140629e-01  5.50429814e-02 -1.38065135e-01]
 [ 7.02680556e-02  1.10144147e-

In [ ]:
#bobot setiap topik terhadap dokumen
dt = pd.DataFrame(lsa_top, columns=['topik1','topik2','topik3'])
dt

topik1    topik2    topik3
0   0.178934  0.101778 -0.092868
1   0.233282  0.033830 -0.126674
2   0.040475  0.094351  0.044837
3   0.163384 -0.029317 -0.087961
4   0.107254  0.098199 -0.070149
5   0.070858  0.048905 -0.053950
6   0.155257  0.123257 -0.254733
7   0.118491  0.255590  0.138909
8   0.073389  0.125618  0.004312
9   0.298673  0.160076 -0.282566
10  0.249076 -0.096657  0.017756
11  0.243139 -0.371254  0.372530
12  0.304213 -0.111676 -0.074990
13  0.084732  0.048487 -0.056703
14  0.096631  0.034798 -0.150896
15  0.093733 -0.012638 -0.063714
16  0.075761  0.006174 -0.032893
17  0.000004 -0.000195 -0.001084
18  0.232141  0.055043 -0.138065
19  0.070268  0.011014 -0.031165
20  0.043583  0.027942 -0.026407
21 -0.000005 -0.000034  0.000779
22  0.000005 -0.000036  0.000730
23  0.157585  0.135529 -0.312062
24  0.000000  0.000000  0.000000
25  0.199908  0.144681 -0.313619
26  0.234929  0.135422 -0.336581
27  0.499684  0.378482 -0.160492
28  0.035503  0.016270 -0.008272
29  0.025761  0.137327  0.167648
30  0.140497  0.539573  0.545414
31  0.177780  0.501231  0.453022
32  0.154860  0.500898  0.451651
33  0.303681  0.136567 -0.369992
34  0.407502 -0.476478  0.416476
35  0.200633  0.213413 -0.025750
36  0.355372 -0.171619  0.010597
37  0.272452 -0.150449  0.023495
38  0.495857 -0.337923  0.169600
39  0.377959 -0.140721  0.003890
40  0.288107 -0.101075  0.063121
41  0.311550 -0.140123  0.038447
42  0.322677 -0.017326 -0.053082
43  0.077203 -0.029537 -0.042101
44  0.311403 -0.040999 -0.059593
45  0.038126  0.008170 -0.020792
46  0.399827 -0.340228  0.214494
47  0.000030 -0.000153 -0.003093
48  0.186447  0.351130  0.161035
49  0.247959  0.194825 -0.086543
50  0.128351  0.077303 -0.158703
51  0.000864 -0.000145  0.000835
52  0.017698 -0.005076 -0.004735
53  0.071322  0.021348 -0.055138

In [ ]:
SV = lsa_model.components_
print(SV)
print(SV.shape) # (no_of_topics*no_of_words)

[[ 5.18442742e-02  4.31090272e-02  1.20196584e-02 ... -2.90654063e-06
   1.45216186e-02  1.64707565e-02]
 [ 3.99361877e-02  5.06541808e-03  1.30497463e-02 ... -1.93873879e-05
  -2.39682007e-03  7.11485454e-03]
 [-8.85814851e-02 -2.20992183e-02 -1.83468542e-03 ...  4.49537229e-04
  -1.30544185e-02 -3.45411307e-02]]
(3, 361)


In [ ]:
#bobot setiap kata terhadap topik
label=[]
for i in range (1,362):
  masukan = f"kata ke-{i}"
  label.append(masukan)
topik = pd.DataFrame(SV,columns=label)
topik.rename(index={0:"topik1",1:"topik2",2:"topik3"})

kata ke-1  kata ke-2  kata ke-3  kata ke-4  kata ke-5  kata ke-6  \
topik1   0.051844   0.043109   0.012020   0.016471   0.139229   0.007424   
topik2   0.039936   0.005065   0.013050   0.007115   0.281476   0.047682   
topik3  -0.088581  -0.022099  -0.001835  -0.034541   0.156999   0.064097   

        kata ke-7  kata ke-8  kata ke-9  kata ke-10  ...  kata ke-352  \
topik1   0.070192   0.050304   0.004664    0.022973  ...     0.019633   
topik2  -0.003388   0.029871   0.009649   -0.001475  ...     0.003444   
topik3  -0.020068  -0.081913   0.000459   -0.005094  ...    -0.014139   

        kata ke-353  kata ke-354  kata ke-355  kata ke-356  kata ke-357  \
topik1      0.04181     0.056534     0.109283     0.002332     0.015079   
topik2     -0.02784     0.010794     0.057984     0.004825     0.011006   
topik3      0.00493    -0.017921    -0.070440     0.000229    -0.024853   

        kata ke-358  kata ke-359  kata ke-360  kata ke-361  
topik1     0.050437    -0.000003     0.014522     0.016471  
topik2    -0.012832    -0.000019    -0.002397     0.007115  
topik3    -0.009909     0.000450    -0.013054    -0.034541  

[3 rows x 361 columns]